In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('play_tennis.csv')
df.head()

   Unnamed: 0 day   outlook  temp humidity    wind play
0           0  D1     Sunny   Hot     High    Weak   No
1           1  D2     Sunny   Hot     High  Strong   No
2           2  D3  Overcast   Hot     High    Weak  Yes
3           3  D4      Rain  Mild     High    Weak  Yes
4           4  D5      Rain  Cool   Normal    Weak  Yes

In [3]:
df.drop(columns=['day'], inplace=True)

In [4]:
df

    Unnamed: 0   outlook  temp humidity    wind play
0            0     Sunny   Hot     High    Weak   No
1            1     Sunny   Hot     High  Strong   No
2            2  Overcast   Hot     High    Weak  Yes
3            3      Rain  Mild     High    Weak  Yes
4            4      Rain  Cool   Normal    Weak  Yes
5            5      Rain  Cool   Normal  Strong   No
6            6  Overcast  Cool   Normal  Strong  Yes
7            7     Sunny  Mild     High    Weak   No
8            8     Sunny  Cool   Normal    Weak  Yes
9            9      Rain  Mild   Normal    Weak  Yes
10          10     Sunny  Mild   Normal  Strong  Yes
11          11  Overcast  Mild     High  Strong  Yes
12          12  Overcast   Hot   Normal    Weak  Yes
13          13      Rain  Mild     High  Strong   No

In [5]:
# First we find Probabilit of yes and no

# P(Yes)
# P(No)

In [6]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [19]:
p_yes = 9/14
p_no = 5/14

In [20]:
print(p_yes)
print(p_no)

0.6428571428571429
0.35714285714285715

### For Outlook

In [9]:
# Outlook

pd.crosstab(df['outlook'], df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [10]:
p_outlook_overcast_no = 0
p_outlook_rain_no = 2/5
p_outlook_sunny_no = 3/5


p_outlook_overcast_yes = 4/9
p_outlook_rain_yes = 3/9
p_outlook_sunny_yes = 2/9

### For Temprature

In [11]:
pd.crosstab(df['temp'], df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [12]:
p_temp_cool_no = 1/5
p_temp_hot_no = 2/5
p_temp_mild_no = 2/5

p_temp_cool_yes = 3/9
p_temp_hot_yes = 2/9
p_temp_mild_yes = 4/9

### For Humidity

In [13]:
pd.crosstab(df['humidity'], df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [14]:
p_humidity_high_no = 4/5
p_humidity_normal_no = 1/5

p_humidity_high_yes = 3/9
p_humidity_normal_yes = 6/9

### For Wind

In [15]:
pd.crosstab(df['wind'], df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [17]:
p_wind_strong_no = 3/5
p_wind_weak_no = 2/5

p_wind_strong_yes = 3/9
p_wind_weak_yes = 6/9

# Problem 1:

### Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
#### Play or No Play?

### Solution

#### P(Yes | Sunny,Hot,High,Weak)=P(Sunny | Yes) * P(Hot|Yes) * P(High|Yes) * P(Weak | Yes) * P(Yes)

#### P(No | Sunny,Hot,High,Weak)=P(Sunny |No) * P(Hot|No) * P(High|No) * P(Weak | No) * P(No)

#### Compare and decide using the Maximum a posteriori rule

In [24]:
# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak

p_play_yes = p_outlook_sunny_yes * p_temp_hot_yes * p_humidity_high_yes * p_wind_weak_yes * p_yes
print(p_play_yes)

p_play_no = p_outlook_sunny_no * p_temp_hot_no * p_humidity_high_no * p_wind_weak_no * p_no
print(p_play_no)

if p_play_yes > p_play_no:
    print("Play")
else:
    print("No Play")

0.007054673721340387
0.02742857142857143
No Play

# Problem 2

### Outlook=Overcast, Temp=Cold, Humidity=Low, Wind=Weak
#### Play or No Play?

### Solution

#### P(Yes | Overcast,Cold,Low,Weak)=P(Overcast | Yes) * P(Cold |Yes) * P(Low | Yes) * P(Weak | Yes) * P(Yes)

#### P(No | Overcast,Cold, Low,Weak)=P(Overcast | No) * P(Cold | No) * P(Low | No) * P(Weak | No) * P(No)

#### Compare and decide using the Maximum a posteriori rule

In [25]:
p_play_yes2 = p_outlook_overcast_yes * p_temp_cool_yes * p_humidity_normal_yes * p_wind_weak_yes * p_yes
print(p_play_yes2)

p_play_no2 = p_outlook_overcast_no * p_temp_cool_no * p_humidity_normal_no * p_wind_weak_no * p_no
print(p_play_no2)

if p_play_yes2 > p_play_no2:
    print("Play")
else:
    print("No Play")

0.042328042328042326
0.0
Play