In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import VotingRegressor

In [2]:
df = pd.read_csv('Boston.csv')

df.head()

,Unnamed: 0,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
0,1,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,2,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,3,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,4,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,5,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [3]:
df.shape

(506, 15)

In [4]:
df = df.drop('Unnamed: 0', axis = 1)

In [5]:
df.sample(3)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,black,lstat,medv
314,0.36920,0.0,9.90,0,0.544,6.567,87.3,3.6023,4,304,18.4,395.69,9.28,23.8
17,0.78420,0.0,8.14,0,0.538,5.990,81.7,4.2579,4,307,21.0,386.75,14.67,17.5
12,0.09378,12.5,7.87,0,0.524,5.889,39.0,5.4509,5,311,15.2,390.50,15.71,21.7

In [6]:
df.shape

(506, 14)

In [7]:
X = df.iloc[:, 0:13]
y = df.iloc[:, -1]

In [8]:
X.shape

(506, 13)

In [9]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
svr = SVR()

In [10]:
estimators = [('lr', lr),('dt', dt),('SVM', svr)]

In [11]:
for est in estimators:
    score = cross_val_score(est[1], X, y, scoring='r2', cv = 10)
    print(est[0], np.round(np.mean(score),2))

lr 0.2
dt -0.07
SVM -0.41

In [12]:
vr = VotingRegressor(estimators)
score = cross_val_score(vr, X, y, scoring = 'r2', cv = 10 )
print(np.round(np.mean(score),2))

0.46

In [14]:
for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            vr = VotingRegressor(estimators=estimators, weights=[i, j,k])
            x = cross_val_score(vr, X,y, cv=10, scoring='r2' )
            print("for i={}, j={},k={}".format(i, j,k),np.round(np.mean(x),2))

for i=1, j=1,k=1 0.44
for i=1, j=1,k=2 0.33
for i=1, j=1,k=3 0.26
for i=1, j=2,k=1 0.4
for i=1, j=2,k=2 0.41
for i=1, j=2,k=3 0.36
for i=1, j=3,k=1 0.33
for i=1, j=3,k=2 0.39
for i=1, j=3,k=3 0.35
for i=2, j=1,k=1 0.44
for i=2, j=1,k=2 0.4
for i=2, j=1,k=3 0.34
for i=2, j=2,k=1 0.42
for i=2, j=2,k=2 0.44
for i=2, j=2,k=3 0.4
for i=2, j=3,k=1 0.34
for i=2, j=3,k=2 0.35
for i=2, j=3,k=3 0.41
for i=3, j=1,k=1 0.45
for i=3, j=1,k=2 0.43
for i=3, j=1,k=3 0.37
for i=3, j=2,k=1 0.46
for i=3, j=2,k=2 0.45
for i=3, j=2,k=3 0.44
for i=3, j=3,k=1 0.44
for i=3, j=3,k=2 0.45
for i=3, j=3,k=3 0.38

## Using Same Algorithm

In [15]:
dt1 = DecisionTreeRegressor(max_depth = 1)
dt2 = DecisionTreeRegressor(max_depth = 3)
dt3 = DecisionTreeRegressor(max_depth = 5)
dt4 = DecisionTreeRegressor(max_depth = 7)
dt5 = DecisionTreeRegressor(max_depth = None)

In [20]:
estimators = [('dt1', dt1),('dt2',dt2),('dt3', dt3),('dt4',dt4),('dt5',dt5)]

In [21]:
for estimator in estimators:
    score = cross_val_score(estimator[1], X, y, scoring='r2', cv = 10)
    print(estimator[0], np.round(np.mean(score),2))

dt1 -0.85
dt2 -0.11
dt3 0.03
dt4 -0.04
dt5 -0.37

In [22]:
vr = VotingRegressor(estimators)
score = cross_val_score(vr, X, y, scoring = 'r2', cv = 10)
print('Voting Regressor', np.round(np.mean(score), 2))

Voting Regressor 0.18