In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.datasets import load_iris

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import cross_val_score

In [2]:
data_iris = load_iris()

In [3]:
df = pd.DataFrame(data = data_iris.data, columns=data_iris.feature_names)
df['target'] = data_iris.target

In [7]:
df.sample(10)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
1,4.9,3.0,1.4,0.2,0
79,5.7,2.6,3.5,1.0,1
21,5.1,3.7,1.5,0.4,0
56,6.3,3.3,4.7,1.6,1
0,5.1,3.5,1.4,0.2,0
30,4.8,3.1,1.6,0.2,0
17,5.1,3.5,1.4,0.3,0
130,7.4,2.8,6.1,1.9,2
29,4.7,3.2,1.6,0.2,0
38,4.4,3.0,1.3,0.2,0

In [10]:
new_df = df[df['target'] != 0][['sepal length (cm)','sepal width (cm)','target']]

In [11]:
new_df.shape

(100, 3)

In [13]:
new_df.head()

    sepal length (cm)  sepal width (cm)  target
50                7.0               3.2       1
51                6.4               3.2       1
52                6.9               3.1       1
53                5.5               2.3       1
54                6.5               2.8       1

In [26]:
X = new_df.iloc[:, 0:2]
y = new_df.iloc[:, -1]

In [27]:
clf1 = LogisticRegression()
clf2 = RandomForestClassifier()
clf3 = KNeighborsClassifier()

In [28]:
estimators = [('lr', clf1), ('rf', clf2), ('knn', clf3)]

In [35]:
for estimator in estimators:
    print(estimator)
    scores = cross_val_score(estimator[1], X, y, cv = 10, scoring = 'accuracy')
    print(estimator[0], np.round(np.mean(scores),2))
    print()

('lr', LogisticRegression())
lr 0.75

('rf', RandomForestClassifier())
rf 0.62

('knn', KNeighborsClassifier())
knn 0.62

In [36]:
from sklearn.ensemble import VotingClassifier

## Hard Voting

In [38]:
vc = VotingClassifier(estimators=estimators)
x = cross_val_score(vc, X, y, cv = 10, scoring = 'accuracy')
print(np.round(np.mean(x),2))

0.67

## Soft Votting

In [40]:
vc1 = VotingClassifier(estimators=estimators, voting='soft')
x = cross_val_score(vc1, X, y, cv = 10, scoring = 'accuracy')
print(np.round(np.mean(x),2))

0.66

## Weigth Voting

In [42]:
for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            vc = VotingClassifier(estimators=estimators, voting='soft', weights=[i, j,k])
            x = cross_val_score(vc, X,y, cv=10, scoring='accuracy' )
            print("for i={}, j={},k={}".format(i, j,k),np.round(np.mean(x),2))

for i=1, j=1,k=1 0.66
for i=1, j=1,k=2 0.64
for i=1, j=1,k=3 0.66
for i=1, j=2,k=1 0.62
for i=1, j=2,k=2 0.63
for i=1, j=2,k=3 0.65
for i=1, j=3,k=1 0.62
for i=1, j=3,k=2 0.62
for i=1, j=3,k=3 0.64
for i=2, j=1,k=1 0.69
for i=2, j=1,k=2 0.67
for i=2, j=1,k=3 0.67
for i=2, j=2,k=1 0.64
for i=2, j=2,k=2 0.63
for i=2, j=2,k=3 0.65
for i=2, j=3,k=1 0.62
for i=2, j=3,k=2 0.63
for i=2, j=3,k=3 0.63
for i=3, j=1,k=1 0.7
for i=3, j=1,k=2 0.69
for i=3, j=1,k=3 0.69
for i=3, j=2,k=1 0.67
for i=3, j=2,k=2 0.64
for i=3, j=2,k=3 0.65
for i=3, j=3,k=1 0.65
for i=3, j=3,k=2 0.64
for i=3, j=3,k=3 0.65

In [44]:
from sklearn.svm import SVC

In [46]:
from sklearn.datasets import make_classification

X, y = make_classification(n_samples=1000, n_features=20, n_informative=15, n_redundant=5, random_state=2)

svm1 = SVC(probability=True, kernel='poly', degree=1)
svm2 = SVC(probability=True, kernel='poly', degree=2)
svm3 = SVC(probability=True, kernel='poly', degree=3)
svm4 = SVC(probability=True, kernel='poly', degree=4)
svm5 = SVC(probability=True, kernel='poly', degree=5)

estimators = [('svm', svm1), ('svm2', svm2), ('svm3', svm3), ('svm4', svm4), ('svm5', svm5) ]

for estimator in estimators:
    x = cross_val_score(estimator[1], X, y, cv=10, scoring='accuracy')
    print(estimator[0],np.round(np.mean(x),2))

svm 0.85
svm2 0.85
svm3 0.89
svm4 0.81
svm5 0.86

In [50]:
vc2 = VotingClassifier(estimators=estimators, voting = 'soft')
x = cross_val_score(vc2, X, y, cv = 10, scoring='accuracy')
print(x)
print()
print(np.round(np.mean(x),2))

[0.93 0.94 0.94 0.95 0.87 0.95 0.91 0.92 0.9  0.97]

0.93